version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
slide_show = true
mtr = true
chiselsandbits = true
simplylight = true
londonunderground = true
chipped = true
jsblock = true
extshape = true
dragonlib = true
mishanguc = true
snowrealmagic = true
yuushya = true
mtrsteamloco = true
tcwm = true
trafficcraft = true
searchlight = true
minecraft = true
msd = true
